nodejs:
  applicationPort: 8080
  aadIdentityName: em
  image: 'hmctspublic.azurecr.io/em/icp:latest'
  readinessDelay: 30
  readinessTimeout: 5
  readinessPeriod: 15
  readinessFailureThreshold: 10
  livenessDelay: 30
  livenessTimeout: 5
  livenessPeriod: 15
  livenessFailureThreshold: 10
  environment:
    REFORM_SERVICE_NAME: em-icp-api
    REFORM_TEAM: em-icp-api
    REDIS_HOST: em-icp-redis-cache-{{ .Values.global.environment }}.redis.cache.windows.net
    REDIS_PORT: 6380
    USE_REDIS: true
    REDIS_USE_TLS: true
    RATE_LIMIT_TIME: 15000
    RATE_LIMITE_MAX: 10
    IDAM_API_BASE_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    em-icp:
      resourceGroup: em-icp
      secrets:
        - redis-password
        - microservicekey-em-icp
        - AppInsightsInstrumentationKey

redis:
  enabled: false
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false

tags:
  pr: false
